CC=g++ -Wall

PROG1=2_6_1_FloatingDecimalToFloatingBinary

2_6_1:
	${CC} -o out/${PROG1}.o src/${PROG1}.cpp

PROG2=2_6_2_1_SumUpVsSumDown

2_6_2_1:
	${CC} -o out/${PROG2}.o src/${PROG2}.cpp

PROG3=2_2_2_OverflowExample

2_6_2_2:
	${CC} -o out/${PROG3}.o src/${PROG3}.cpp

PROG4=2_4_1_1_ExponentiationSeries

2_4_1_1:
	${CC} -o out/${PROG4}.o src/${PROG4}.cpp

PROG5=2_4_1_2_ExponentiationRecursion

2_4_1_2:
	${CC} -o out/${PROG5}.o src/${PROG5}.cpp

PROG6=2_4_3_2_StandardDeviation

2_4_3_2:
	${CC} -o out/${PROG6}.o src/${PROG6}.cpp


